server:
  port: 8092
---
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.61:1521:xe
    username: daldal
    password: daldal
---
mybatis:
  mapper-locations: classpath:mappers/**/*.xml

spring:
  data:
    mongodb:
      host: 192.168.1.28
      port: 27017
